services:
    terminal42_leads.command.export:
        class: Terminal42\LeadsBundle\Command\ExportCommand
        arguments:
            - "@database_connection"
            - "@contao.framework"
        tags:
            - { name: console.command }

    terminal42_leads.export_target_manager:
        class: Terminal42\LeadsBundle\ExportTargetManager

    terminal42_leads.export_target.browser:
        class: Terminal42\LeadsBundle\ExportTarget\BrowserTarget
        tags:
            - { name: terminal42_leads.export_target, alias: browser }

    terminal42_leads.export_target.local:
        class: Terminal42\LeadsBundle\ExportTarget\LocalTarget
        tags:
            - { name: terminal42_leads.export_target, alias: local }
