services:
    terminal42_leads.command.export:
        class: Terminal42\LeadsBundle\Command\ExportCommand
        arguments:
            - "@database_connection"
            - "@contao.framework"
        tags:
            - { name: console.command }
